# libretro CI
variables:
  GIT_SUBMODULE_STRATEGY: normal

.core-defs:
  variables:
    CORENAME: ppsspp
    CORE_ARGS: -DLIBRETRO=ON

.linux-defs:
  variables:
    EXTRA_PATH: lib

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

#Desktop
libretro-build-linux-x86_64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs
    - .linux-defs

# Android
libretro-build-android-armeabi-v7a:
  extends:
    - .libretro-android-cmake-armeabi-v7a
    - .core-defs

libretro-build-android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs

libretro-build-android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs

libretro-build-android-x86:
  extends:
    - .libretro-android-cmake-x86
    - .core-defs
